### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `typos --format brief`

### CODE REVIEW

**Comment by ianspektor** [comment]
Hey @kianmeng! Sorry for the huge delay, there were some security implications of having an external PR merged that we hadn't been able to sort out yet. We can merge this if you resolve the conflicts in the notebooks. Thanks for your contribution!

**Comment by kianmeng** [comment]
@ianspektor I can't seem to clone this repo due to this error:

```
$ git clone https://github.com/google/temporian
Cloning into 'temporian'...
remote: Enumerating objects: 24853, done.
remote: Counting objects: 100% (2115/2115), done.
remote: Compressing objects: 100% (645/645), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 5989 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

Even after trying the solutions suggested [here](https://stackoverflow.com/questions/59282476/error-rpc-failed-curl-92-http-2-stream-0-was-not-closed-cleanly-protocol-erro), it still won't work for me after over 30 attempts.

Perhaps you guys want to resolve this on your own?

**Comment by ianspektor** [comment]
Hey @kianmeng - I can clone it correctly. Have you tried [these](https://stackoverflow.com/questions/66366582/github-unexpected-disconnect-while-reading-sideband-packet)?

**Comment by kianmeng** [comment]
> Hey @kianmeng - I can clone it correctly. Have you tried [these](https://stackoverflow.com/questions/66366582/github-unexpected-disconnect-while-reading-sideband-packet)?

Not working for me, still the same issue, even after tweaking the recommended solutions suggested in the link.

**Comment by ianspektor** [comment]
Hey @kianmeng! Cloning is working fine for everyone in the team, and for external contributors too. I'd suggest to keep trying out the solutions recommended in StackOverflow/GH issues. Sorry to not be of much help here!

**Comment by kianmeng** [comment]
@ianspektor Sorry for the delay, I have managed to clone without issue right now. 
I will close the PR since all the typos have been resolved. Thanks.

**Pull request closed without merging**
